# Generated by Django 4.2.5 on 2023-12-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProxyWithoutVideo',
            fields=[
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='PostProxyWithVideo',
            fields=[
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
    ]
