# Generated by Django 4.2.5 on 2023-09-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoacademiaco',
            name='popup',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materias',
            name='popup',
            field=models.URLField(blank=True, null=True),
        ),
    ]
