# Generated by Django 4.2.5 on 2023-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_artigoacademiaco_popup_materias_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroPublicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('popup', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
